###
#   Server config
###

server:
  port: 8080


###
#   Database Settings
###
spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/springmongosec
#    username: root
#    password:
#    driver-class-name: com.mysql.jdbc.Driver

jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
###
#   H2 Settings
###
#h2:
#  console:
#    enabled: true
#    path: /console
#    settings:
#      trace: false
#      web-allow-others: false


###
#   Kafka Settings
###
kafka:
#  bootstrap-servers: localhost:2222, localhost:3333
  bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
  topic:
    avro: springmongosecdemo

###
#   Logging configuration
###
logging:
  level:
    root: debug